export const TODO_SET_ALL = 'TODO_SET_ALL'
export const TODO_SET = 'TODO_SET'
export const TODO_APPEND = 'TODO_APPEND'
export const TODO_CHANGE = 'TODO_CHANGE'
export const TODO_REMOVE = 'TODO_REMOVE'

export const TODO_FETCH_ALL = 'TODO_FETCH_ALL'
export const TODO_CREATE = 'TODO_CREATE'
export const TODO_DELETE = 'TODO_DELETE'

export default {
  TODO_SET_ALL,
  TODO_SET,
  TODO_APPEND,
  TODO_CHANGE,
  TODO_REMOVE,
  TODO_FETCH_ALL,
  TODO_CREATE,
  TODO_DELETE
}
